export enum errors {
  FAILED_TO_DECODE_TOKEN = "FAILED_TO_DECODE_TOKEN",
  FAILED_TO_AUTHENTICATE = "FAILED_TO_AUTHENTICATE",
  UNAUTHENTICATED = "UNAUTHENTICATED",
  UNAUTHORISED = "UNAUTHORISED",
  NOT_FOUND = "NOT_FOUND",
  NO_CHAT_SELF = "NO_CHAT_SELF",
  EXISTING_CHAT = "EXISTING_CHAT",
  INVALID_PARAMS = "INVALID_PARAMS"
}
